spring:
  datasource
  url: jdbc:h2:tcp://localhost/~/test
  driver-class-name: org.h2.Driver
  username: hygoni
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    showSql: true
  messages:
    basename: lang/exception
    encoding: UTF-8
  jwt:
    secret: govlepel@$&